/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(halow_frame_equalizer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9cdead21a2a138b80b3b7b5daf6832af)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/halow/halow_frame_equalizer.h>
// pydoc.h is automatically generated in the build directory
#include <halow_frame_equalizer_pydoc.h>

void bind_halow_frame_equalizer(py::module& m)
{

    using halow_frame_equalizer    = gr::halow::halow_frame_equalizer;


    py::class_<halow_frame_equalizer, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<halow_frame_equalizer>>(m, "halow_frame_equalizer", D(halow_frame_equalizer))

        .def(py::init(&halow_frame_equalizer::make),
           D(halow_frame_equalizer,make)
        )
        



        ;




}








