/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(halow_sync_short.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(560fbfd8e854d26af19d403c86974d45)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/halow/halow_sync_short.h>
// pydoc.h is automatically generated in the build directory
#include <halow_sync_short_pydoc.h>

void bind_halow_sync_short(py::module& m)
{

    using halow_sync_short    = gr::halow::halow_sync_short;


    py::class_<halow_sync_short, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<halow_sync_short>>(m, "halow_sync_short", D(halow_sync_short))

        .def(py::init(&halow_sync_short::make),
           D(halow_sync_short,make)
        )
        



        ;




}








