/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(halow_sync_long.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(820554f23a7009355e3f87d5a252569d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/halow/halow_sync_long.h>
// pydoc.h is automatically generated in the build directory
#include <halow_sync_long_pydoc.h>

void bind_halow_sync_long(py::module& m)
{

    using halow_sync_long    = gr::halow::halow_sync_long;


    py::class_<halow_sync_long, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<halow_sync_long>>(m, "halow_sync_long", D(halow_sync_long))

        .def(py::init(&halow_sync_long::make),
           D(halow_sync_long,make)
        )
        



        ;




}








